# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170515_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
