# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170515_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
