# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170515_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='ip',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='port',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
