# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170522_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
